version: '3.8'

services:
  question-classifier:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: question-classifier-app
    ports:
      - "8501:8501"
    environment:
      # API Keys - Set these in your .env file or pass as environment variables
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      
      # Streamlit Configuration
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      
      # Python Configuration
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    volumes:
      # Mount the current directory for development (optional)
      - .:/app
      # Mount logs directory to persist CrewAI logs
      - ./logs:/app/logs
      # Mount uploads directory for file uploads
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - question-classifier-network


networks:
  question-classifier-network:
    driver: bridge

